spring.application.name=app-realtime-chat

spring.mvc.static-path-pattern=/static/**

# PostgreSQL Connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/chat_db
spring.datasource.username=postgres
spring.datasource.password=Faizan27

# JPA / Hibernate Settings
# 'update' tells Spring to automatically create or update your tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
# This prints the actual SQL queries to your IntelliJ console so you can see what it's doing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.google.client_id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client_secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email

# Cloudinary Keys
cloudinary.cloud_name=YOUR_CLOUD_NAME
cloudinary.api_key=YOUR_API_KEY
cloudinary.api_secret=YOUR_API_SECRET

# Increase Multipart File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# This allows the session cookie to be sent from Azure to your localhost
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
# Force Update 1